site_name: BRB Mobilidade
nav:
  - Home: index.md
  - Apresentações: Apresentações/apresentacao.md
  - Planejamento: planejamento.md
  - Pré-rastreabilidade:
    - Rich Picture: Pre-rastreabilidade/richpicture.md
  - Elicitação de requisitos: 
    - O que é elicitar requisitos?: Elicitação/elicitação.md
    - Priorização: Elicitação/priorização.md
    - Observação: Elicitação/observação.md
    - Introspecção: Elicitação/introspeccao.md
  
  - Modelagem de Requisitos:
    - Cenários: Modelagem/cenarios.md
    - Especificação Suplementar: Modelagem/especificacao_suplementar.md
    - Caso de uso: Modelagem/casosdeuso.md
    - Léxicos: Modelagem/lexicos.md
    - NFR: Modelagem/nfr.md
    - Backlog e História de Usuário: Modelagem/backlog-historia.md
  - Análise:
    - Validação: Analise/Validacao/prototipo.md
    - Verificação: 
      - Backlog e História de Usuário: Analise/Verificacao/verificacaoBacklog.md
      - Especificação Suplementar: Analise/Verificacao/verificacaoEspecificacao.md
      - Léxicos: Analise/Verificacao/verificacaoLexicos.md
      - Rich Picture: Analise/Verificacao/verificacaoRichPicture.md
      - Cenários: Analise/Verificacao/verificacaoCenarios.md
      - NFR: Analise/Verificacao/verificacaoNFR.md
      - Casos de uso: Analise/Verificacao/verificacaoCasoDeUso.md
theme:
  name: null
  custom_dir: mkdocs-material/material
  language: pt
  palette:
    scheme: default
    primary: indigo
    accent: light blue
  font:
    text: Roboto
  icon: 
    logo: material/library
    repo: fontawesome/brands/github
  favicon: images/brblogo.png
  features:
    - instant
  extra:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2020.1-BRBmobilidade
plugins:
  - search:
      separator: '[\s\-\.]+'
repo_url: https://github.com/Requisitos-de-Software/2020.1-BRBmobilidade
markdown_extensions:
  - toc:
      permalink: false
edit_uri: ""