site_name: BRB Mobilidade
nav:
  - Home: index.md
  - Planejamento: planejamento.md
  - Pré-rastreabilidade:
    - Rich Picture: Pre-rastreabilidade/richpicture.md
  - Elicitação de requisitos: elicitação.md
  - Técnicas: 
    - Introspecção: introspeccao.md
theme:
  name: null
  custom_dir: mkdocs-material/material
  language: pt
  palette:
    scheme: default
    primary: indigo
    accent: light blue
  font:
    text: Roboto
  icon: 
    logo: material/library
    repo: fontawesome/brands/github
  favicon: images/brblogo.png
  features:
    - instant
  extra:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2020.1-BRBmobilidade
plugins:
  - search:
      separator: '[\s\-\.]+'
repo_url: https://github.com/Requisitos-de-Software/2020.1-BRBmobilidade
markdown_extensions:
  - toc:
      permalink: false
edit_uri: ""